/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Copy2ClipboardTools: typeof import('./src/components/Copy2ClipboardTools.vue')['default']
    PaginationTools: typeof import('./src/components/page/paginationTools.vue')['default']
    PassowordTools: typeof import('./src/components/PassowordTools.vue')['default']
    RespTools: typeof import('./src/components/RespTools.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchTool: typeof import('./src/components/page/searchTool.vue')['default']
    TableTool: typeof import('./src/components/page/tableTool.vue')['default']
  }
}
